version: '3'

services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=clair
      - POSTGRES_USER=clair
      - POSTGRES_DB=clair
    #postgres:9.6.23
    image: postgres@sha256:0c544a9de02082855b4ee592d59685403a8b51acdcd559cef4140ad9ef1396bd
    network_mode: host
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data:rw 

  clair:
    container_name: clair
    depends_on:
      - postgres
    #clair:4.2.0
    image: quay.io/projectquay/clair@sha256:917df97fd182bf45d880649285b45e730a52e6cca4b70e3b0a810d4e39d43c9a
    network_mode: host 
    restart: unless-stopped
    volumes:
      - ./clair/reports/:/reports/:rw
      - ./clair/config/config_v4.2.0.yaml:/config/config.yaml:ro
      - /tmp:/tmp

  registry:
    container_name: registry
    #registry: 2.7.1
    image: registry@sha256:42043edfae481178f07aa077fa872fcc242e276d302f4ac2026d9d2eb65b955f
    network_mode: host
    volumes:
      - registry-volume:/var/lib/registry:rw
    
volumes:
  postgres-volume:
  registry-volume: