# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test

on:
   workflow_dispatch:
     
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: add hosts entry
      run: |
        cat /etc/hosts
        
